package utopia.echo.model.response.openai

import utopia.echo.model.response.TokenUsage
import utopia.flow.generic.factory.FromModelFactoryWithSchema
import utopia.flow.generic.model.immutable.{Model, ModelDeclaration}
import utopia.flow.generic.model.mutable.DataType.IntType

object OpenAiTokenUsageStatistics extends FromModelFactoryWithSchema[OpenAiTokenUsageStatistics]
{
	// ATTRIBUTES   -----------------
	
	override lazy val schema: ModelDeclaration = ModelDeclaration("input_tokens" -> IntType, "output_tokens" -> IntType)
	
	
	// IMPLEMENTED  -----------------
	
	override protected def fromValidatedModel(model: Model): OpenAiTokenUsageStatistics = {
		val input = model("input_tokens").getInt
		val output = model("output_tokens").getInt
		apply(input, model("input_tokens_details")("cached_tokens").getInt, output,
			model("output_tokens_details")("reasoning_tokens").getInt, model("total_tokens").intOr { input + output })
	}
}

/**
  * Contains information about token usage in a single request-response pair
  * @author Mikko Hilpinen
  * @since 04.04.2025, v1.3
  * @param input The total number of tokens used in model input
  * @param cached The number of input tokens that were cached
  * @param output The total number of tokens generated by the model
  * @param reasoning The number of output tokens that were used in the reasoning phase
  * @param total Total number of tokens used in this interaction (input + output)
  */
case class OpenAiTokenUsageStatistics(input: Int, cached: Int, output: Int, reasoning: Int, total: Int)
	extends TokenUsage
