package utopia.echo.model.response.openai

import utopia.echo.model.response.TokenUsage
import utopia.echo.model.tokenization.TokenCount
import utopia.flow.generic.factory.{FromModelFactory, FromModelFactoryWithSchema}
import utopia.flow.generic.model.immutable.{Model, ModelDeclaration}
import utopia.flow.generic.model.mutable.DataType.IntType
import utopia.flow.generic.model.template.ModelConvertible
import utopia.flow.generic.casting.ValueConversions._

object OpenAiTokenUsageStatistics
{
	// ATTRIBUTES   -----------------
	
	/**
	 * A zero usage -statistics
	 */
	lazy val zero = apply(TokenCount.zero, TokenCount.zero, TokenCount.zero, TokenCount.zero, TokenCount.zero)
	
	
	// COMPUTED ---------------------
	
	/**
	 * @return A JSON parser to use with the /responses API endpoint
	 */
	def responsesParser: FromModelFactory[OpenAiTokenUsageStatistics] = ResponsesResponseParser
	/**
	 * @return A JSON parser to use with the /chat/completions API endpoint
	 */
	def chatCompletionParser: FromModelFactory[OpenAiTokenUsageStatistics] = ChatCompletionResponseParser
	
	
	// NESTED   -------------------------
	
	private object ResponsesResponseParser extends FromModelFactoryWithSchema[OpenAiTokenUsageStatistics]
	{
		// ATTRIBUTES   -----------------
		
		override lazy val schema: ModelDeclaration =
			ModelDeclaration("input_tokens" -> IntType, "output_tokens" -> IntType)
		
		
		// IMPLEMENTED  ----------------
		
		override protected def fromValidatedModel(model: Model): OpenAiTokenUsageStatistics = {
			val input = model("input_tokens").getInt
			val output = model("output_tokens").getInt
			OpenAiTokenUsageStatistics(input, model("input_tokens_details")("cached_tokens").getInt, output,
				model("output_tokens_details")("reasoning_tokens").getInt,
				model("total_tokens").intOr { input + output })
		}
	}
	
	private object ChatCompletionResponseParser extends FromModelFactoryWithSchema[OpenAiTokenUsageStatistics]
	{
		// ATTRIBUTES   ------------------------
		
		override lazy val schema: ModelDeclaration =
			ModelDeclaration("completion_tokens" -> IntType, "prompt_tokens" -> IntType)
		
		
		// IMPLEMENTED  ------------------------
		
		override protected def fromValidatedModel(model: Model): OpenAiTokenUsageStatistics = {
			val input = model("prompt_tokens").getInt
			val output = model("completion_tokens").getInt
			// TODO: Could add support for prompt_tokens_details|completion_tokens_details/audio_tokens
			OpenAiTokenUsageStatistics(input,
				model("prompt_cache_hit_tokens").intOr { model("prompt_tokens_details")("cached_tokens").getInt },
				output, model("completion_tokens_details")("reasoning_tokens").getInt,
				model("total_tokens").intOr { input + output })
		}
	}
}

/**
  * Contains information about token usage in a single request-response pair
  * @author Mikko Hilpinen
  * @since 04.04.2025, v1.3
  * @param input The total number of tokens used in model input
  * @param cached The number of input tokens that were cached
  * @param output The total number of tokens generated by the model
  * @param reasoning The number of output tokens that were used in the reasoning phase
  * @param total Total number of tokens used in this interaction (input + output)
  */
case class OpenAiTokenUsageStatistics(input: TokenCount, cached: TokenCount, output: TokenCount, reasoning: TokenCount,
                                      total: TokenCount)
	extends TokenUsage with ModelConvertible
{
	// IMPLEMENTED  ---------------------
	
	override def toModel: Model = Model.from("input_tokens" -> input.value, "output_tokens" -> output.value,
		"total_tokens" -> total.value, "input_tokens_details" -> Model.from("cached_tokens" -> cached.value),
		"output_tokens_details" -> Model.from("reasoning_tokens" -> reasoning.value))
	
	
	// OTHER    -------------------------
	
	def +(other: OpenAiTokenUsageStatistics) = OpenAiTokenUsageStatistics(input + other.input, cached + other.cached,
		output + other.output, reasoning + other.reasoning, total + other.total)
}
