package utopia.genesis.handling.event

import utopia.genesis.event.ConsumeEvent

import scala.annotation.unused
import scala.language.implicitConversions

/**
  * Represents a (listener's) choice to either consume an item, or to keep it unconsumed
  * @author Mikko Hilpinen
  * @since 05/02/2024, v3.6
  */
sealed trait ConsumeChoice
{
	// ABSTRACT -----------------------
	
	/**
	  * @return The consume event to generate based on this choice.
	  *         None if the choice was not to consume the related item.
	  */
	def eventIfConsumed: Option[ConsumeEvent]
}

object ConsumeChoice
{
	// IMPLICIT -----------------------
	
	implicit def preserveByDefault(@unused u: Unit): ConsumeChoice = Preserve
	
	
	// NESTED   -----------------------
	
	/**
	  * Represents a choice not to consume an item
	  */
	case object Preserve extends ConsumeChoice
	{
		override def eventIfConsumed: Option[ConsumeEvent] = None
	}
	
	object Consume
	{
		/**
		  * @param by A string that represents this consumer / consume event (call-by-name)
		  * @return A choice to consume the related item
		  */
		def apply(by: => String): Consume = new Consume(ConsumeEvent(by))
	}
	/**
	  * Represents a choice to consume an item
	  * @param consumeEvent Consume event generated by this choice
	  */
	case class Consume(consumeEvent: ConsumeEvent) extends ConsumeChoice
	{
		override def eventIfConsumed: Option[ConsumeEvent] = Some(consumeEvent)
	}
}
