package utopia.terra.controller.coordinate.world

/**
  * Common trait for factory classes that accept vectors and produce Earth surface points
  * @author Mikko Hilpinen
  * @since 6.9.2023, v1.0
  * @tparam V Type of aerial vector representations accepted by this factory
  * @tparam A Type of aerial world points generated by this factory
  */
trait VectorToAerialPoint[-V, +A]
{
	/**
	  * @param vector A vector
	  * @return A world point that matches that vector;
	  *         Not bound to the earth's surface.
	  */
	def aerialVector(vector: V): A
}
