package utopia.terra.controller.coordinate.world

/**
  * Common trait for factory classes that accept vectors and produce Earth surface points
  * @author Mikko Hilpinen
  * @since 6.9.2023, v1.0
  * @tparam V2D Type of surface vector representations accepted by this factory
  * @tparam V3D Type of aerial vector representations accepted by this factory
  * @tparam S Type of Earth surface points generated by this factory
  * @tparam A Type of aerial world points generated by this factory
  */
trait VectorToWorldPoint[-V2D, -V3D, +S, +A] extends VectorToSurfacePoint[V2D, S] with VectorToAerialPoint[V3D, A]
