package utopia.terra.controller.coordinate.world

/**
  * Common trait for factory classes that accept vectors and produce Earth surface points
  * @author Mikko Hilpinen
  * @since 6.9.2023, v1.0
  * @tparam V Type of vector representations accepted by this factory
  * @tparam S Type of Earth surface points generated by this factory
  */
trait VectorToSurfacePoint[-V, +S]
{
	/**
	  * @param vector A vector
	  * @return A surface point that matches that vector
	  */
	def surfaceVector(vector: V): S
}
