package utopia.reach.form

import utopia.firmament.context.color.ColorContext
import utopia.firmament.image.SingleColorIcon
import utopia.firmament.localization.LocalizedString
import utopia.flow.collection.immutable.Pair
import utopia.flow.generic.model.immutable.Value
import utopia.flow.util.logging.Logger
import utopia.flow.view.immutable.caching.Lazy
import utopia.flow.view.mutable.eventful.MutableOnce
import utopia.paradigm.color.ColorRole
import utopia.reach.component.factory.Mixed
import utopia.reach.component.interactive.button.image.ImageAndTextButton
import utopia.reach.component.label.text.TextLabel
import utopia.reach.component.template.ReachComponent
import utopia.reach.container.multi.Stack
import utopia.reach.container.wrapper.{AlignFrame, Framing}
import utopia.reach.window.NotificationWindow.NotificationWindowFactory

import scala.concurrent.{ExecutionContext, Future}

/**
 * An enumeration used for wrapping / representing form field output values and/or validation results.
 *
 * @author Mikko Hilpinen
 * @since 07.09.2025, v1.7
 */
sealed trait FormFieldOut

object FormFieldOut
{
	// ATTRIBUTES   --------------------
	
	/**
	 * An empty successful output
	 */
	lazy val empty = Success(Value.empty)
	
	
	// OTHER    ------------------------
	
	/**
	 * @param output Output to generate lazily
	 * @return A delayed output, that will call the specified function
	 */
	def lazily(output: => FormFieldOut) = Delayed { Future.successful(output) }
	
	/**
	 * Presents a button-based multi-select window for the user
	 * @param context Context for window-creation
	 * @param message Displayed message / prompt (call-by-name, called every time a new dialog is displayed)
	 * @param options Displayed options. Each contains 4 values:
	 *                      1. Button text
	 *                      1. Button color (role)
	 *                      1. Button icon (may be empty)
	 *                      1. Generated output, if that button is pressed
	 * @param default The result generated by default, if the window is closed without selecting any of the options.
	 *                Default = cancel.
	 * @param component Component next to which the selection window should be displayed (optional)
	 * @param windowFactory Implicit factory for constructing the notification windows
	 * @param exc Implicit execution context
	 * @param log Implicit logging implementation
	 * @return A form field output that opens a dialog, allowing the user to choose the output
	 */
	def userChoice(context: ColorContext, message: => LocalizedString,
	               options: Seq[(LocalizedString, ColorRole, SingleColorIcon, FormFieldOut)],
	               default: FormFieldOut = Cancel, component: Option[ReachComponent] = None)
	              (implicit windowFactory: NotificationWindowFactory, exc: ExecutionContext, log: Logger) =
		Delayed {
			val choiceP = MutableOnce(default)
			val window = windowFactory.build(context, component) { factories =>
				factories(Framing).small.build(Stack) { stackF =>
					stackF.related.build(Mixed) { factories =>
						val messageLabel = factories(TextLabel)(message)
						val buttonsArea = factories(AlignFrame).right.build(Stack) { stackF =>
							stackF.related.row.build(ImageAndTextButton) { buttonF =>
								options.map { case (text, color, icon, result) =>
									buttonF(color)(icon, text) { choiceP.value = result }
								}
							}
						}
						Pair(messageLabel, buttonsArea.parent)
					}
				}
			}
			choiceP.flag.onceSet { window.close() }
			window.closeFuture.foreach { _ => choiceP.lock() }
			window.display()
			
			choiceP.future
		}
	
	
	// VALUES   ------------------------
	
	/**
	 * Represents a successfully acquired & accepted form field value
	 * @param value Wrapped value
	 */
	case class Success(value: Value) extends FormFieldOut
	/**
	 * Represents a rejected form field value
	 * @param message Error message to display. May be empty.
	 */
	case class Failure(message: LocalizedString) extends FormFieldOut
	
	/**
	 * When this output is yielded, the form value input-gathering is cancelled without notice.
	 */
	case object Cancel extends FormFieldOut
	
	object Delayed
	{
		/**
		 * @param f A function to call lazily, which prepares the delayed field result
		 *          (which is represented as a future)
		 * @return A delayed output calling 'f' lazily
		 */
		def apply(f: => Future[FormFieldOut]): Delayed = apply(Lazy(f))
	}
	/**
	 * Represents a delayed / multistep output.
	 * Used, for example, when the output needs to be confirmed by the user,
	 * or when other additional input is required.
	 * @param result A future that will yield the eventual form field output to apply.
	 *               May be lazily initialized, so that the additional input / confirmation is only displayed
	 *               when actually necessary.
	 */
	case class Delayed(result: Lazy[Future[FormFieldOut]]) extends FormFieldOut
}