package utopia.flow.operator

import utopia.flow.operator.enumeration.Extreme
import utopia.flow.operator.enumeration.Extreme.{Max, Min}

/**
  * Common trait for factory classes that can specify extreme values
  * @author Mikko Hilpinen
  * @since 8.12.2023, v2.3
  * @tparam A Type of values generated by this factory
  */
trait HasExtremes[+A] extends Any
{
	// ABSTRACT -------------------------
	
	/**
	  * @param extreme Targeted extreme
	  * @return The most extreme value in that direction
	  */
	def apply(extreme: Extreme): A
	
	
	// COMPUTED -------------------------
	
	/**
	  * @return The smallest value in this collection
	  */
	def min = apply(Min)
	/**
	  * @return The largest value in this collection
	  */
	def max = apply(Max)
}
