package utopia.vault.test.app

import utopia.flow.async.context.ThreadPool
import utopia.flow.util.console.ConsoleExtensions._
import utopia.flow.time.Now
import utopia.flow.util.logging.{Logger, SysErrLogger}
import utopia.vault.database.{Connection, ConnectionPool}
import utopia.vault.test.database.access.item.versioned.AccessTestItems
import utopia.vault.test.database.storable.item.VersionedTestItemDbModel
import utopia.vault.test.model.partial.item.VersionedTestItemData

import scala.io.StdIn

/**
  * Tests models generated by Vault Coder
  * @author Mikko Hilpinen
  * @since 04.07.2025, v1.22
  */
object VaultModelsTest extends App
{
	// ATTRIBUTES   ----------------------
	
	private implicit val log: Logger = SysErrLogger
	private implicit val exc: ThreadPool = new ThreadPool("vault-test")
	private implicit val cPool: ConnectionPool = new ConnectionPool()
	
	Connection.modifySettings { _.copy(
		user = StdIn.readNonEmptyLine("Specify DB user. Default = root.").getOrElse("root"),
		password = StdIn.read("Specify DB password").getString
	) }
	
	private val itemModel = VersionedTestItemDbModel
	
	
	// APP CODE --------------------------
	
	cPool { implicit c =>
		val testStartTime = Now.toInstant
		
		// Tests whether DB may be accessed
		c.dbName = "vault_test"
		c.execute("SELECT NULL FROM versioned_test_item")
		
		// Inserts new test items
		val inserted = itemModel.insert(Vector("first", "second", "third").map { name => VersionedTestItemData(name) })
		println("\nInserted: ")
		println(inserted.iterator.map { item => s"${ item.name }: ${ item.id }" }.mkString("\n"))
		
		// Accesses the items
		val read = AccessTestItems.since(testStartTime).pull
		println("\nRead:")
		println(read.iterator.map { item => s"${ item.name }: ${ item.id }" }.mkString("\n"))
		
		assert(inserted.size == read.size)
		assert(inserted.view.map { _.id }.toSet == read.view.map { _.id }.toSet)
		
		// Deprecates the items
		assert(AccessTestItems(inserted.map { _.id }).deprecate)
		
		// Attempts to access again
		assert(AccessTestItems.since(testStartTime).isEmpty)
		assert(AccessTestItems.includingHistory.since(testStartTime).nonEmpty)
		
		println("\nSuccess!")
	}
}
