package utopia.nexus.controller.api.node.extendable

import utopia.access.model.enumeration.Method
import utopia.access.model.enumeration.Status.{MethodNotAllowed, NotImplemented}
import utopia.flow.collection.CollectionExtensions._
import utopia.nexus.controller.api.node.ApiNode
import utopia.nexus.model.api.PathFollowResult
import utopia.nexus.model.api.PathFollowResult.NotFound
import utopia.nexus.model.response.RequestResult

/**
 * Common trait for API nodes which delegate their implementation to
 * [[FollowImplementation]]s and [[UseCaseImplementation]]s.
 *
 * Use this trait if you can't or don't want to specify the ApiNode implementation within a single module
 * (e.g. when creating an extendable framework)
 *
 * @tparam C Type of the required request context
 * @tparam P Type of the local context generated by this node
 *
 * @author Mikko Hilpinen
 * @since 07.11.2025, v2.0, based on ModularResource written 17.6.2021 for v1.6
 */
trait ModularApiNode[-C, P] extends ApiNode[C]
{
	// ABSTRACT ---------------------------
	
	/**
	 * Provides local API node context to a request-execution function.
	 * May apply pre- and/or post-processing.
	 * @param implementation Function that will perform the request-execution and yield a request result
	 * @param context Implicit request context
	 * @return Request result to yield to the client
	 */
	protected def withLocalContext(implementation: P => RequestResult)(implicit context: C): RequestResult
	
	/**
	 * @return The follow implementations used in this resource
	 */
	def followImplementations: Iterable[FollowImplementation[C]]
	/**
	 * @return The use case implementations used in this resource, grouped by method
	 */
	def useCaseImplementations: Map[Method, Iterable[UseCaseImplementation[C, P]]]
	
	
	// IMPLEMENTED  -----------------------
	
	override def allowedMethods = useCaseImplementations.keys
	
	override def follow(step: String)(implicit context: C): PathFollowResult[C] =
		followImplementations.findMap { _(step) }.getOrElse {
			NotFound(s"No implementation exists for following /$step from $name")
		}
	
	override def apply(method: Method, remainingPath: Seq[String])(implicit context: C): RequestResult = {
		val implementations = useCaseImplementations
		implementations.get(method).iterator.flatten.notEmpty match {
			case Some(useCaseIterator) =>
				withLocalContext { localContext =>
					def nextResult(): RequestResult = useCaseIterator.nextOption() match {
						case Some(implementation) => implementation(remainingPath, localContext) { nextResult() }
						case None => NotImplemented -> s"Node \"$name\" contains no implementation for this use-case"
					}
					nextResult()
				}
			// Case: No use-cases specified for this method => Yields 501 or 405
			case None =>
				// Case: No implementations at all => 501
				if (implementations.isEmpty)
					NotImplemented -> s"Node \"$name\" contains no implementation at this time"
				// Case: No implementation for this method => 401
				else
					RequestResult(MethodNotAllowed, s"No implementation exists for $method")
						.mapHeaders { _.withAllowedMethods(implementations.keysIterator.toOptimizedSeq) }
		}
	}
}
